In [46]:
import numpy as np

In [2]:
array_1d = np.array([2,3,4])
print(array_1d)

[2 3 4]


In [7]:
np.zeros((4,5,3),dtype=np.int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [9]:
array = np.full((5,5), 5,dtype=np.int)
print(array)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [11]:
array_multipleof5 = np.arange(5,55,5,dtype=np.int)
print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


In [14]:
array = [[0,1],[1,0]]
n=4
board = np.tile(array,(n//2,n//2))
print(board)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [17]:
list_1=[1,2]
list_2 = [2,3]
array_1 = np.asarray([list_1,list_2])
len(array_1)


2

In [48]:
input_list=[[1,2,3,4,5]]
array_2d =np.array(input_list)


rows = len(array_2d[:, 0])
cols = len(array_2d[0, :])


col_first = array_2d[:,0]
row_first = array_2d[0,:]
col_last = array_2d[:,cols-1]
row_last = array_2d[rows-1,:]

print(col_first)
print(row_first)
print(col_last)
print(row_last)

[1]
[1 2 3 4 5]
[5]
[1 2 3 4 5]


In [49]:
import pandas as pd

In [53]:
series = pd.Series(range(1,5),range(1,5))

In [54]:
print(series)

1    1
2    2
3    3
4    4
dtype: int64


In [55]:
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df_2 = df.sort_values(['month','day'])
print(df_2.head(20))

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
241  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1   0.0   0.00
442  6  5   apr  mon  87.9   24.9   41.6   3.7  10.9  64   3.1   0.0   3.35
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
239  7  5   apr  sun  81.9    3.0    7.9   3.5  13.4  75   1.8   0.0   0.00
469  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0  61.13
470  5  4   apr  sun  91.0   14.6   25.6  12.3  17.6  27   5.8   0.0   0.00
176  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0   4.61
196  6  5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   0.0  10.93
240  6  3   apr  wed  88.0   17.2   43.5   3.8  15.2  51   2.7   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
78   1  2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   0.0   0.00
142  8  6   aug  fri  90.1  108.0  529.8  12.5  21.2  51   8.9   0.0   0.61
184  8  6   

In [75]:
import numpy as np 
import pandas as pd

# Defining the three dataframes indicating the gold, silver, and bronze medal counts
# of different countries
gold = pd.DataFrame({'Country': ['USA', 'France', 'Russia'],
                         'Medals': [15, 13, 9]}
                    )
silver = pd.DataFrame({'Country': ['USA', 'Germany', 'Russia'],
                        'Medals': [29, 20, 16]}
                    )
bronze = pd.DataFrame({'Country': ['France', 'USA', 'UK'],
                        'Medals': [40, 28, 27]}
                        
                    )

df=pd.merge(pd.merge(gold,silver,how='outer',on='Country'),bronze,how='outer',on='Country')
df.fillna(0,inplace=True)
df['Medals'] = df.sum(axis=1)
df.drop(df.columns[[1, 2]], axis=1,inplace=True)

print(df.sort_values('Medals',ascending=False).to_string(index=False))



 Country  Medals
     USA    72.0
  France    53.0
      UK    27.0
  Russia    25.0
 Germany    20.0


In [13]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
#Type your groupby command here
df.head()
df_month_day = df[['month','day','rain','wind']].groupby(['month','day'])

print(df_month_day.mean().to_string())

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000
      mon  0.000000  4.500000
      sat  0.000000  2.350000
      sun  0.000000  2.550000
      thu  0.000000  3.100000
      tue  0.000000  5.850000
      wed  0.000000  3.100000
jan   sat  0.000000  3.100000
      sun  0.000000  0.900000
jul   fri  0.000000  4.300000
      mon  0.000000  3.800000
      sat  0.000000  2.250000
      sun 

In [16]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')
df['XY'] = df['X']*df['Y']
print(df.head(20))

    X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area  XY
0   7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.0  35
1   7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0  28
2   7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0  28
3   8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0  48
4   8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0  48
5   8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0  48
6   8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0  48
7   8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0  48
8   8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0  48
9   7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0  35
10  7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.0  35
11  7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   

In [21]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/vBDCsoHCytUSLKkLvq851k2b8JOCkF')

df_month_day = df[['month','day','rain','wind']].pivot_table(index=['month','day'],aggfunc='mean')

print(df_month_day.to_string())

               rain      wind
month day                    
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000
      mon  0.000000  4.500000
      sat  0.000000  2.350000
      sun  0.000000  2.550000
      thu  0.000000  3.100000
      tue  0.000000  5.850000
      wed  0.000000  3.100000
jan   sat  0.000000  3.100000
      sun  0.000000  0.900000
jul   fri  0.000000  4.300000
      mon  0.000000  3.800000
      sat  0.000000  2.250000
      sun 

In [23]:
import pandas as pd
df = pd.read_csv('https://query.data.world/s/Hfu_PsEuD1Z_yJHmGaxWTxvkz7W_b0')
print(df.isnull().sum())

Ord_id                   0
Prod_id                  0
Ship_id                  0
Cust_id                  0
Sales                   20
Discount                55
Order_Quantity          55
Profit                  55
Shipping_Cost           55
Product_Base_Margin    109
dtype: int64


In [24]:
import numpy as np 

# Given array
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])

# Read the values of m and n
import sys
lines = sys.stdin.readlines()
m = 0
n = 2


a[[m, n]] = a[[n, m]]

# Write your code for swapping here

# Print the array after swapping
print(a)

[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


In [40]:
n=5
array = np.full((n,n), 0,dtype=np.int)


array[0, :] = np.ones(n,dtype=np.int)
array[n-1, :] = np.ones(n,dtype=np.int)
array[:, 0] = np.ones(n,dtype=np.int)
array[:, n-1] = np.ones(n,dtype=np.int)
print(array[:,:3])



[[1 1 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 1 1]]


In [44]:
A = np.array([[2, 6, -1], 
              [1, 2, -2], 
              [-5, 0, 2]])
b = np.array([0, 1, 8])

# compute the inverse
A_inv = np.linalg.inv(A)

# solution: A_inv * b
x = np.dot(A_inv, b)
print(x) # returns [ 0.  0. -1.]

[-2.   0.5 -1. ]


In [45]:
A = np.array([[2, -1, -1], 
              [2, -1, 1], 
              [4, -2, -3]])

b = np.array([1, 0, -1])
print(np.linalg.matrix_rank(A))

2


In [47]:
A = np.array([[4, 7], 
              [9, 6]])

# c is the array of eigenvalues
# v is the matrix with eigenvectors as the columns
c, v = np.linalg.eig(A)
print(c)
print(v)

[-3. 13.]
[[-0.70710678 -0.61394061]
 [ 0.70710678 -0.78935222]]
